### ISSUE TITLE
Wrapper sends execute-requests that don't point to the filestorage-urls of complex inputs

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#35]
Deus-wrapper seems to send to deus some input-data from the wrong location.
It attempts to send input-data from the WPS-server that provided the data, instead of attempting to get it from the file-storage.

To reproduce:
1. complete rebuild of docker-compose
2. send order by specifying a value for each field in frontend:4200/orders

Note the message sent to the actual deus-process from the wps-wrapper.

Logs:

```
acknowledge message
order message handler receiver: {"orderId":1}
2022-10-27 11:13:57,964 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Got new order to handle with wrapper 1
2022-10-27 11:13:57,965 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added literal input constraint for eq-deus schema: SARA_v1.0
2022-10-27 11:13:57,965 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Parsed constraints
2022-10-27 11:13:57,965 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Define the literal constraints for the jobs
2022-10-27 11:13:57,965 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Define the complex constraints for the jobs
2022-10-27 11:13:57,967 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Define the bbox constraints for the jobs
2022-10-27 11:13:57,968 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Process job
2022-10-27 11:13:57,972 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Lookup the process id
2022-10-27 11:13:57,974 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Got the procss id 4
2022-10-27 11:13:57,977 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Created one job
2022-10-27 11:13:57,978 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added literal input for schema: SARA_v1.0
2022-10-27 11:13:57,979 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added complex input (as reference to existing output) for intensity
2022-10-27 11:13:57,980 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added complex input (as reference to existing output) for exposure
2022-10-27 11:13:57,980 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added complex input (as reference to existing output) for fragility
2022-10-27 11:13:57,981 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added job to order
2022-10-27 11:13:57,982 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
2022-10-27 11:13:58,102 [deus-asyncwrapper_shakyground-success_subscription] INFO  org.n52.geoprocessing.wps.client.WPSClientSession: CONNECT
2022-10-27 11:13:58,326 [deus-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Start calling the wps itself
```

```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd" response="document" mode="sync" service="WPS" version="2.0.0">
    <ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.DeusProcess</ows:Identifier>
    <wps:Input id="intensity">
        <wps:Reference xlink:href="https://rz-vm140.gfz-potsdam.de:443/wps/RetrieveResultServlet?id=7e5c6d34-d127-4fb6-a1dd-bde7cd283efcshakeMapFile.545c0244-f542-430b-b318-04bd8094250e" mimeType="text/xml"></wps:Reference>
    </wps:Input>
    <wps:Input id="exposure">
        <wps:Reference xlink:href="https://rz-vm140.gfz-potsdam.de:443/wps/RetrieveResultServlet?id=10a3c70e-dca5-4195-a7a8-d2b7889928beselectedRowsGeoJson.80adf9db-c4a3-4cee-9aaa-5edbf7caac7a" mimeType="application/json"></wps:Reference>
    </wps:Input>
    <wps:Input id="schema">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>SARA_v1.0</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="fragility">
        <wps:Reference xlink:href="https://rz-vm140.gfz-potsdam.de:443/wps/RetrieveResultServlet?id=ccd54f64-8fed-4be6-8284-c1c8e7f21135selectedRows.3c7519d2-b406-4f99-b7fa-5dcf6d1112bd" mimeType="application/json"></wps:Reference>
    </wps:Input>
    <wps:Output id="merged_output" transmission="reference" mimeType="application/json" encoding="UTF-8"></wps:Output>
    <wps:Output id="shapefile_summary" transmission="reference" mimeType="application/WMS" encoding="UTF-8"></wps:Output>
    <wps:Output id="meta_summary" transmission="reference" mimeType="application/json" encoding="UTF-8"></wps:Output>
</wps:Execute>
```

**Comment by MichaelLangbein** [comment]
Wait! This might be because I didn't manually re-compile the async-wrapper before doing my docker compose up ... testing that now ...

**Comment by MichaelLangbein** [comment]
Indeed, that seems to be it. Now I get a new error from the upstream services:
```
2022-10-27 11:48:59,669 [pulsar-client-io-2-1] INFO  com.scurrilous.circe.checksum.Crc32cIntChecksum: SSE4.2 CRC32C provider initialized
order message handler receiver: {"orderId":1}
2022-10-27 11:48:59,687 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got new order to handle with wrapper 1
2022-10-27 11:48:59,702 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for shakyground vsgrid: FromSeismogeotechnicsMicrozonation
2022-10-27 11:48:59,702 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for shakyground gmpe: AbrahamsonEtAl2015SInter
2022-10-27 11:48:59,702 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added complex input constraint for shakyground quakeMLFile
2022-10-27 11:48:59,703 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Parsed constraints
2022-10-27 11:48:59,703 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the literal constraints for the jobs
2022-10-27 11:48:59,703 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the complex constraints for the jobs
2022-10-27 11:48:59,707 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the bbox constraints for the jobs
2022-10-27 11:48:59,707 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Process job
2022-10-27 11:48:59,712 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Lookup the process id
2022-10-27 11:48:59,715 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got the procss id 3
2022-10-27 11:48:59,717 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Created one job
2022-10-27 11:48:59,718 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for vsgrid: FromSeismogeotechnicsMicrozonation
2022-10-27 11:48:59,719 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for gmpe: AbrahamsonEtAl2015SInter
2022-10-27 11:48:59,720 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added complex input (as value) for quakeMLFile
2022-10-27 11:48:59,721 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added job to order
2022-10-27 11:48:59,721 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
2022-10-27 11:48:59,895 [shakyground-asyncwrapper_new-order_subscription] INFO  org.n52.geoprocessing.wps.client.WPSClientSession: CONNECT
2022-10-27 11:49:00,274 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start calling the wps itself
2022-10-27 11:49:00,437 [shakyground-asyncwrapper_new-order_subscription] INFO  WPSProcess: <wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd" response="document" mode="sync" service="WPS" version="2.0.0"><ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.ShakygroundProcess</ows:Identifier><wps:Input id="quakeMLFile"><wps:Data mimeType="application/vnd.geo+json" encoding="UTF-8">{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-72.3538,-31.9306]},"properties":{"publicID":"quakeml:quakeledger/80674883","preferredOriginID":"quakeml:quakeledger/80674883","preferredMagnitudeID":"quakeml:quakeledger/80674883","type":"earthquake","description.text":"expert","origin.publicID":"quakeml:quakeledger/80674883","origin.time.value":"2019-01-01T00:00:00.000000Z","origin.depth.value":"12.7","origin.creationInfo.value":"GFZ","magnitude.publicID":"quakeml:quakeledger/80674883","magnitude.mag.value":"8.0","magnitude.type":"MW","magnitude.creationInfo.value":"GFZ","focalMechanism.publicID":"quakeml:quakeledger/80674883","focalMechanism.nodalPlanes.nodalPlane1.strike.value":"9.0","focalMechanism.nodalPlanes.nodalPlane1.dip.value":"20.0","focalMechanism.nodalPlanes.nodalPlane1.rake.value":"90.0","focalMechanism.nodalPlanes.preferredPlane":"nodalPlane1"},"id":"quakeml:quakeledger/80674883"}]}</wps:Data></wps:Input><wps:Input id="gmpe"><wps:Data mimeType="text/xml"><wps:LiteralValue>AbrahamsonEtAl2015SInter</wps:LiteralValue></wps:Data></wps:Input><wps:Input id="vsgrid"><wps:Data mimeType="text/xml"><wps:LiteralValue>FromSeismogeotechnicsMicrozonation</wps:LiteralValue></wps:Data></wps:Input><wps:Output id="shakeMapFile" transmission="reference" mimeType="text/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8"></wps:Output><wps:Output id="shakeMapFile" transmission="reference" mimeType="application/WMS" encoding="UTF-8"></wps:Output></wps:Execute>
org.n52.geoprocessing.wps.client.model.Result@3922e897
[Id: shakeMapFile
Title: null
Abstract: null
Metadata: []
Format: MimeType: text/xml
Schema: http://earthquake.usgs.gov/eqcenter/shakemap
Encoding: UTF-8

Format: MimeType: text/xml
Schema: http://earthquake.usgs.gov/eqcenter/shakemap
Encoding: UTF-8

Reference: Href: https://rz-vm140.gfz-potsdam.de:443/wps/RetrieveResultServlet?id=9127835d-eb6a-41a6-ae0b-e9b40c1d6628shakeMapFile.0265baea-3a2f-46a9-8864-98784d6d65d0

, Id: shakeMapFile
Title: null
Abstract: null
Metadata: []
Format: MimeType: application/WMS
Schema: null
Encoding: UTF-8

Format: MimeType: application/WMS
Schema: null
Encoding: UTF-8

Reference: Href: https://rz-vm140.gfz-potsdam.de:443/wps/RetrieveResultServlet?id=9127835d-eb6a-41a6-ae0b-e9b40c1d6628shakeMapFile.2579b2cc-1eea-43cd-b012-e353dc56f641

]
2022-10-27 11:49:02,949 [shakyground-asyncwrapper_new-order_subscription] INFO  WPSProcess: Start extracting results from the wps
2022-10-27 11:49:02,950 [shakyground-asyncwrapper_new-order_subscription] INFO  WPSProcess: Stored result for shakeMapFile
2022-10-27 11:49:02,950 [shakyground-asyncwrapper_new-order_subscription] INFO  WPSProcess: Stored result for shakeMapFile
2022-10-27 11:49:02,950 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Finished calling the wps itself
2022-10-27 11:49:02,950 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Finished mapping the outputs
Exception in thread "shakyground-asyncwrapper_new-order_subscription" java.lang.NoClassDefFoundError: java/net/http/HttpClient
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fetchContent(AbstractWrapper.kt:440)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.ensureStoredLink(AbstractWrapper.kt:410)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:345)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:259)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:56)
        at org.n.riesgos.asyncwrapper.events.OrderMessageHandler.handleMessage(OrderMessageHandler.kt:23)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: java.net.http.HttpClient
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
```

Will muck around with the pom.xml to provide that missing dependency ... though it's weird that it wasn't in there in the first place ...

**Comment by MichaelLangbein** [comment]
Might be because I'm locally building with java-11?
I'll try upgrading to java-17.
... Damn; requires re-installing maven ... working on it ...

**Comment by MichaelLangbein** [comment]
Updated asyncwrapper-build to be run inside of container.
Shouldn't degrade performance, because compiled wrapper is shared between all other containers.

**Comment by MichaelLangbein** [comment]
Indeed, with the new wrapper installed, I get a new error - which consists of deus being unable to resolve the new url `http://localhost/api/v1/files/FB889D7C38C7F0702F3EEA9944414AECC78D312D`. 

This is as expected; closing issue.
