### ISSUE TITLE
On smaller machines sometimes `Document changed during save`

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#42]
Occurs often when several wrappers can handle an order at the same time.

```
async-shakyground_wrapper-1  | order message handler receiver: {"orderId":1}
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,259 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got new order to handle with wrapper 1
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,273 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for shakyground vsgrid: USGSSlopeBasedTopographyProxy
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,273 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for shakyground gmpe: MontalvaEtAl2016SInter
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,274 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added complex input constraint for shakyground quakeMLFile
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,274 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Parsed constraints
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,274 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the literal constraints for the jobs
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,274 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the complex constraints for the jobs
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,279 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the bbox constraints for the jobs
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,279 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Process job
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,285 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Lookup the process id
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,289 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got the procss id 4
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,292 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Created one job
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,294 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for vsgrid: USGSSlopeBasedTopographyProxy
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,295 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for gmpe: MontalvaEtAl2016SInter
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,297 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added complex input (as value) for quakeMLFile
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,298 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added job to order
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,298 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,514 [shakyground-asyncwrapper_new-order_subscription] INFO  org.n52.geoprocessing.wps.client.WPSClientSession: CONNECT
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,821 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: WPS call failed
async-shakyground_wrapper-1  | 2023-01-16 10:19:19,821 [shakyground-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: WPS call failed because of: Got HTTP error code, response: Exceptions: [	Code: NoApplicableCode	Text: java.util.ConcurrentModificationException: Document changed during save
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver.process(Saver.java:302)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$TextSaver.write(Saver.java:1817)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.ensure(Saver.java:2521)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.access$100(Saver.java:2419)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver$OutputStreamImpl.read(Saver.java:2570)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.read(Saver.java:2504)
async-shakyground_wrapper-1  | 	at java.io.InputStream.read(InputStream.java:101)
async-shakyground_wrapper-1  | 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1262)
async-shakyground_wrapper-1  | 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1236)
async-shakyground_wrapper-1  | 	at org.n52.wps.server.handler.RequestHandler.handle(RequestHandler.java:431)
async-shakyground_wrapper-1  | 	at org.n52.wps.server.WebProcessingService.doGet(WebProcessingService.java:223)
async-shakyground_wrapper-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
async-shakyground_wrapper-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
async-shakyground_wrapper-1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
async-shakyground_wrapper-1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
async-shakyground_wrapper-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
async-shakyground_wrapper-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
async-shakyground_wrapper-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
async-shakyground_wrapper-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207)
async-shakyground_wrapper-1  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
async-shakyground_wrapper-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
async-shakyground_wrapper-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:169)
async-shakyground_wrapper-1  | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:232)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
async-shakyground_wrapper-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
async-shakyground_wrapper-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
async-shakyground_wrapper-1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
async-shakyground_wrapper-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
async-shakyground_wrapper-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
async-shakyground_wrapper-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
async-shakyground_wrapper-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
async-shakyground_wrapper-1  | 	at java.lang.Thread.run(Thread.java:750)	Locator: null]
async-shakyground_wrapper-1  | org.n52.geoprocessing.wps.client.WPSClientException: Got HTTP error code, response: Exceptions: [	Code: NoApplicableCode	Text: java.util.ConcurrentModificationException: Document changed during save
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver.process(Saver.java:302)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$TextSaver.write(Saver.java:1817)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.ensure(Saver.java:2521)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.access$100(Saver.java:2419)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver$OutputStreamImpl.read(Saver.java:2570)
async-shakyground_wrapper-1  | 	at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.read(Saver.java:2504)
async-shakyground_wrapper-1  | 	at java.io.InputStream.read(InputStream.java:101)
async-shakyground_wrapper-1  | 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1262)
async-shakyground_wrapper-1  | 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1236)
async-shakyground_wrapper-1  | 	at org.n52.wps.server.handler.RequestHandler.handle(RequestHandler.java:431)
async-shakyground_wrapper-1  | 	at org.n52.wps.server.WebProcessingService.doGet(WebProcessingService.java:223)
async-shakyground_wrapper-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
async-shakyground_wrapper-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
async-shakyground_wrapper-1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
async-shakyground_wrapper-1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
async-shakyground_wrapper-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
async-shakyground_wrapper-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
async-shakyground_wrapper-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
async-shakyground_wrapper-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
async-shakyground_wrapper-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207)
async-shakyground_wrapper-1  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
async-shakyground_wrapper-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
async-shakyground_wrapper-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:169)
async-shakyground_wrapper-1  | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:232)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
async-shakyground_wrapper-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
async-shakyground_wrapper-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
async-shakyground_wrapper-1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
async-shakyground_wrapper-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
async-shakyground_wrapper-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
async-shakyground_wrapper-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
async-shakyground_wrapper-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
async-shakyground_wrapper-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
async-shakyground_wrapper-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
async-shakyground_wrapper-1  | 	at java.lang.Thread.run(Thread.java:750)	Locator: null]
async-shakyground_wrapper-1  | 	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveResponseOrExceptionReportInpustream(WPSClientSession.java:564)
async-shakyground_wrapper-1  | 	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveCapsViaGET(WPSClientSession.java:536)
async-shakyground_wrapper-1  | 	at org.n52.geoprocessing.wps.client.WPSClientSession.connect(WPSClientSession.java:170)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.process.wps.WPSClientService.establishWPSConnection(WPSClientService.kt:17)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:335)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:262)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:57)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.events.OrderMessageHandler.handleMessage(OrderMessageHandler.kt:23)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
async-shakyground_wrapper-1  | 	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
async-shakyground_wrapper-1  | 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by nbrinckm** [comment]
I realized that also several times - and it was on my todo list to check it out in more detail.

I had the impression that there are some concurrent modifications within the jar, but I missed to find some time for further checks.

**Comment by MichaelLangbein** [comment]
https://github.com/riesgos/async/pull/37

**Comment by MichaelLangbein** [comment]
@Benni: looking into where those xml exceptions are coming from

**Comment by nbrinckm** [comment]
It is like always that those problems occur within the WPSClientSession connect method.
In almost all of my tests it is the way that one of the wrappers go through that successfully, while the other 3 that are triggered by the example order file from the frontend run into an issue when connecting.

It seems that it is mostly associated with the GetCapabilities request - and it seems to be just the case when all of the wrappers try to do that more or less at the very same time.

With that I tried the following things:
- remove the getInstance call in the establishWPSConnection method, so that we get a fresh WpsClientSession every time
- mounted the jar files in readonly mount into the containers
- migrated back to a java 8 image

None of the ideas get me a single millimeter closer to a working solution.

**Comment by nbrinckm** [comment]
Using a debian based image (vs the alpine one) also gives no benefit. Errors still occur.

**Comment by nbrinckm** [comment]
Maybe a small progress: I fetched the capabilities without using the wps client. Error still happens. So I guess it is not a thing with the wps client - and more a problem with the server that we use inside of the docker-compose.

I try now to add some handling around the connect calls.
