### ISSUE TITLE
Error on https://riesgos.52north.org/javaps/service?service=WPS&request=Execute&version=2.0.0&identifier=org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#52]
Does anyone else get this too?

When starting a process from the frontend, currently I get no further than to the shakemap-resampler:

```
2023-02-13 15:31:44,103 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  ShakemapResampler: get inputs for shakemapresampler
2023-02-13 15:31:44,103 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Process job
2023-02-13 15:31:44,104 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Lookup the process id
2023-02-13 15:31:44,104 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Got the procss id 8
2023-02-13 15:31:44,105 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Created one job
2023-02-13 15:31:44,106 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added literal input for random_seed: 1
2023-02-13 15:31:44,106 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added complex input (as reference to existing output) for intensity_file
2023-02-13 15:31:44,107 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Added job to order
2023-02-13 15:31:44,107 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
2023-02-13 15:31:44,108 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: Start calling the wps itself under https://riesgos.52north.org/javaps/service/org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler
2023-02-13 15:31:44,185 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] ERROR org.n52.geoprocessing.wps.client.WPSClientSession: Could not fetch processdescription for process: org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler
org.n52.geoprocessing.wps.client.WPSClientException: Could not decode Inputstream.
        at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:620)
        at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveResponseOrExceptionReportInpustream(WPSClientSession.java:559)
        at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveDescriptionViaGET(WPSClientSession.java:633)
        at org.n52.geoprocessing.wps.client.WPSClientSession.describeProcess(WPSClientSession.java:291)
        at org.n52.geoprocessing.wps.client.WPSClientSession.getProcessDescription(WPSClientSession.java:230)
        at org.n.riesgos.asyncwrapper.process.wps.WPSProcess.runProcess(WPSProcess.kt:24)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:337)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:262)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:57)
        at org.n.riesgos.asyncwrapper.events.ProcessInputMessageHandler.handleMessage(ProcessInputMessageHandler.kt:25)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[31,48]
Message: unexpected tag: {http://www.opengis.net/ows/2.0}ValuesReference
        at org.n52.iceland.util.XmlFactories.unexpectedTag(XmlFactories.java:142)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readLiteralDataDomain(DescribeProcessResponseDecoder.java:395)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readLiteralData(DescribeProcessResponseDecoder.java:338)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readInput(DescribeProcessResponseDecoder.java:494)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readProcess(DescribeProcessResponseDecoder.java:166)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readProcessOffering(DescribeProcessResponseDecoder.java:119)
        at org.n52.geoprocessing.wps.client.decoder.stream.DescribeProcessResponseDecoder.readProcessOfferings(DescribeProcessResponseDecoder.java:98)
        at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readProcessOfferingsResponse(WPSResponseReader.java:110)
        at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readElement(WPSResponseReader.java:50)
        at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:618)
        ... 12 common frames omitted
2023-02-13 15:31:44,185 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: WPS call failed
2023-02-13 15:31:44,185 [shakemap-resampler-asyncwrapper_shakyground-success_subscription] INFO  AbstractWrapper: WPS call failed because of: processDescription.inputs must not be null
java.lang.NullPointerException: processDescription.inputs must not be null
        at org.n.riesgos.asyncwrapper.process.wps.WPSProcess.runProcess(WPSProcess.kt:28)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:337)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:262)
        at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:57)
        at org.n.riesgos.asyncwrapper.events.ProcessInputMessageHandler.handleMessage(ProcessInputMessageHandler.kt:25)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
        at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
        at java.base/java.lang.Thread.run(Thread.java:831)
acknowledge message
2023-02-13 15:31:57,295 [pulsar-timer-8-1] INFO  org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: [new-order] [shakemap-resampler-asyncwrapper_new-order_subscription] [2e6d4] Prefetched messages: 0 --- Consume throughput received: 0.02 msgs/s --- 0.00 Mbit/s --- Ack sent rate: 0.02 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0
2023-02-13 15:31:57,296 [pulsar-timer-9-1] INFO  org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: [shakyground-success] [shakemap-resampler-asyncwrapper_shakyground-success_subscription] [0026e] Prefetched messages: 0 --- Consume throughput received: 0.03 msgs/s --- 0.00 Mbit/s --- Ack sent rate: 0.03 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0
```

A request to the WPS directly fails, too:
```bash
curl --location --request POST 'https://riesgos.52north.org/javaps/service?service=WPS&request=Execute&version=2.0.0&identifier=org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler' \
--header 'Content-Type: application/xml' \
--data-raw '<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0"	xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wpsExecute.xsd" service="WPS" version="2.0.0" response="document" mode="sync">
    <ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler</ows:Identifier>
    <wps:Input id="intensity_file">
        <wps:Reference xlink:href="https://raw.githubusercontent.com/riesgos/System_Reliability/master/testinputs/shakemap.xml" mimeType="text/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8" />
    </wps:Input>
    <wps:Input id="random_seed">
        <wps:Data mimeType="text/plain">123</wps:Data>
    </wps:Input>
    <wps:Output id="intensity_output_file" mimeType="text/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8" transmission="value"/>
</wps:Execute>'
```
Yields:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsAll.xsd" version="1.1.0">
    <ows:Exception exceptionCode="NoApplicableCode">
        <ows:ExceptionText>An error occured when parsing the request! Message: Content is not allowed in prolog.</ows:ExceptionText>
        <ows:ExceptionText>[EXCEPTION]: 
org.n52.shetland.ogc.ows.exception.NoApplicableCodeException: An error occured when parsing the request! Message: Content is not allowed in prolog.
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:144)
	at org.n52.iceland.binding.AbstractXmlBinding.decode(AbstractXmlBinding.java:82)
	at org.n52.iceland.binding.pox.PoxBinding.parseRequest(PoxBinding.java:95)
	at org.n52.iceland.binding.pox.PoxBinding.doPostOperation(PoxBinding.java:83)
	at org.n52.iceland.service.Service.post(Service.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:208)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:274)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:130)
	... 61 more
</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

**Comment by bpross-52n** [comment]
The Request (taken from above comment) works for me with Postman:
`<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0"	xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wpsExecute.xsd" service="WPS" version="2.0.0" response="document" mode="sync">
    <ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.shakemap_sampler</ows:Identifier>
    <wps:Input id="intensity_file">
        <wps:Reference xlink:href="https://raw.githubusercontent.com/riesgos/System_Reliability/master/testinputs/shakemap.xml" mimeType="text/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8" />
    </wps:Input>
    <wps:Input id="random_seed">
        <wps:Data mimeType="text/plain">123</wps:Data>
    </wps:Input>
    <wps:Output id="intensity_output_file" mimeType="text/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8" transmission="value"/>
</wps:Execute>`

**Comment by MichaelLangbein** [comment]
Hi @bpross-52n : turns out this wasn't a problem with the wps at all. DLR's intranet doesn't allow me to send stuff to riesgos.52north.org - I think it strips off the request body or something. I've opened a ticket with out IT-department. Thanks a lot!
