### ISSUE TITLE
Tsunami wrapper in production: runs indefinitely

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#98]
In production, the tsunami wrapper never gets further than the state `running`.

Here's the docker-log for the tsunami wrapper after receiving an order:

```
order message handler receiver: {"orderId":1}
2023-05-03 10:19:18,329 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got new order to handle with wrapper 1
2023-05-03 10:19:18,498 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami mag: 6.85
2023-05-03 10:19:18,499 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami lon: -71.37228
2023-05-03 10:19:18,500 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami lat: -30.92143
2023-05-03 10:19:18,501 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Parsed constraints
2023-05-03 10:19:18,511 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the literal constraints for the jobs
2023-05-03 10:19:18,515 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the complex constraints for the jobs
2023-05-03 10:19:18,516 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the bbox constraints for the jobs
2023-05-03 10:19:18,517 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Process job
2023-05-03 10:19:18,536 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Lookup the process id
2023-05-03 10:19:18,555 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got the process id 4
2023-05-03 10:19:18,571 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Created one job
2023-05-03 10:19:18,578 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for mag: 6.85
2023-05-03 10:19:18,583 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for lon: -71.37228
2023-05-03 10:19:18,587 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for lat: -30.92143
2023-05-03 10:19:18,591 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added job to order
2023-05-03 10:19:18,593 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
2023-05-03 10:19:18,597 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: retrieve getCapabilities document from  https://riesgos.52north.org/wps (retries: 0)
2023-05-03 10:19:19,782 [tsunami-asyncwrapper_new-order_subscription] INFO  org.n52.geoprocessing.wps.client.WPSClientSession: CONNECT
2023-05-03 10:19:20,787 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: retrieved getCapabilities document from https://riesgos.52north.org/wps (retries: 0)
2023-05-03 10:19:20,787 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start calling the wps itself under https://riesgos.52north.org/wps/get_tsunamap
2023-05-03 10:19:20,790 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: retrieve wps process description for get_tsunamap (retries: 0)
2023-05-03 10:19:21,048 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: retrieved wps process description for get_tsunamap (retries: 0)
2023-05-03 10:19:21,139 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: <wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd" response="document" mode="sync" service="WPS" version="2.0.0"><ows:Identifier>get_tsunamap</ows:Identifier><wps:Input id="lat"><wps:Data mimeType="text/xml"><wps:LiteralValue>-30.92143</wps:LiteralValue></wps:Data></wps:Input><wps:Input id="lon"><wps:Data mimeType="text/xml"><wps:LiteralValue>-71.37228</wps:LiteralValue></wps:Data></wps:Input><wps:Input id="mag"><wps:Data mimeType="text/xml"><wps:LiteralValue>6.85</wps:LiteralValue></wps:Data></wps:Input><wps:Output id="tsunamap" transmission="reference" mimeType="application/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8"></wps:Output></wps:Execute>
2023-05-03 10:19:21,142 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 0)
2023-05-03 10:19:22,721 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 1)
2023-05-03 10:19:23,875 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 2)
2023-05-03 10:19:30,727 [pulsar-timer-5-1] INFO  org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: [new-order] [tsunami-asyncwrapper_new-order_subscription] [ac2a0] Prefetched messages: 1 --- Consume throughput received: 0.02 msgs/s --- 0.00 Mbit/s --- Ack sent rate: 0.00 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0

```

**Comment by MichaelLangbein** [comment]
Does *not* work: 
```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd" response="document" mode="sync" service="WPS" version="2.0.0">
    <ows:Identifier>get_tsunamap</ows:Identifier>
    <wps:Input id="lat">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>-30.92143</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="lon">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>-71.37228</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="mag">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>6.85</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Output id="tsunamap" transmission="reference" mimeType="application/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8"></wps:Output>
</wps:Execute>
```


Doesn't work, either ... even though it's one of AWIs pre-calculated simulations:
```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd" response="document" mode="sync" service="WPS" version="2.0.0">
    <ows:Identifier>get_tsunamap</ows:Identifier>
    <wps:Input id="lat">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>-32.9011</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="lon">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>-71.8152</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="mag">
        <wps:Data mimeType="text/xml">
            <wps:LiteralValue>8.5</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Output id="tsunamap" transmission="reference" mimeType="application/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8"></wps:Output>
</wps:Execute>
```

**Comment by bpross-52n** [comment]
I just tested this execute request successfully:
````
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" service="WPS" version="1.0.0">
    <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">get_tsunamap</p0:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">lon</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">lon</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>-71.8004</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">lat</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">lat</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>-32.9143</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">mag</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">mag</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>8.0</wps:LiteralData>
            </wps:Data>
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:ResponseDocument storeExecuteResponse="true" status="true">
            <wps:Output mimeType="application/xml" asReference="true">
                <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">tsunamap</p0:Identifier>
            </wps:Output>
        </wps:ResponseDocument>
    </wps:ResponseForm>
</wps:Execute>
````

**Comment by MichaelLangbein** [comment]
@arnevogt , @bpross-52n : my second request in [this comment](https://github.com/riesgos/async/issues/98#issuecomment-1533025490) didn't work because it used WPS-V2. With WPS-V1 syntax it does indeed work fine.

@arnevogt : did you deploy your changes to production?

**Comment by MichaelLangbein** [comment]
@arnevogt : I have deployed the latest state of main branch to production.

Tsunami wrapper does work fine if the input is an earthquake that tsuami-wps knows about. 
However, if it isn't known (i.e if mag < 8), the wrapper still keeps hanging in `running` state.

Here's the tsunami-wrapper log for an order with mag < 8:
```
2023-05-15 09:11:09,422 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got new order to handle with wrapper 3
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami mag: 6.5
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami lon: -69.13947
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input constraint for tsunami lat: -33.59573
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Parsed constraints
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the literal constraints for the jobs
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the complex constraints for the jobs
2023-05-15 09:11:09,425 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Define the bbox constraints for the jobs
2023-05-15 09:11:09,426 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Process job
2023-05-15 09:11:09,427 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Lookup the process id
2023-05-15 09:11:09,432 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Got the process id 3
2023-05-15 09:11:09,436 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Created one job
2023-05-15 09:11:09,438 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for mag: 6.5
2023-05-15 09:11:09,442 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for lon: -69.13947
2023-05-15 09:11:09,447 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added literal input for lat: -33.59573
2023-05-15 09:11:09,449 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Added job to order
2023-05-15 09:11:09,450 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start mapping to wps inputs
2023-05-15 09:11:09,450 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: retrieve getCapabilities document from  https://riesgos.52north.org/wps (retries: 0)
2023-05-15 09:11:09,452 [tsunami-asyncwrapper_new-order_subscription] INFO  org.n52.geoprocessing.wps.client.WPSClientSession: CONNECT
2023-05-15 09:11:09,569 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: retrieved getCapabilities document from https://riesgos.52north.org/wps (retries: 0)
2023-05-15 09:11:09,569 [tsunami-asyncwrapper_new-order_subscription] INFO  AbstractWrapper: Start calling the wps itself under https://riesgos.52north.org/wps/get_tsunamap
2023-05-15 09:11:09,569 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: retrieve wps process description for get_tsunamap (retries: 0)
2023-05-15 09:11:09,666 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: retrieved wps process description for get_tsunamap (retries: 0)
2023-05-15 09:11:09,670 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: <wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd" service="WPS" version="1.0.0"><ows:Identifier>get_tsunamap</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>lat</ows:Identifier><wps:Data><wps:LiteralData>-33.59573</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>lon</ows:Identifier><wps:Data><wps:LiteralData>-69.13947</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>mag</ows:Identifier><wps:Data><wps:LiteralData>6.5</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:ResponseDocument><wps:Output asReference="true" mimeType="application/xml" schema="http://earthquake.usgs.gov/eqcenter/shakemap" encoding="UTF-8"><ows:Identifier>tsunamap</ows:Identifier></wps:Output></wps:ResponseDocument></wps:ResponseForm></wps:Execute>
2023-05-15 09:11:09,671 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 0)
2023-05-15 09:11:09,766 [tsunami-asyncwrapper_new-order_subscription] WARN  WPSProcess: wps process returned an exception, retryable: true
org.n52.geoprocessing.wps.client.WPSClientException: Could not decode Inputstream.
	at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:620)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveResponseOrExceptionReportInpustream(WPSClientSession.java:588)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveDataViaPOST(WPSClientSession.java:659)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveExecuteResponseViaPOST(WPSClientSession.java:690)
	at org.n52.geoprocessing.wps.client.WPSClientSession.execute(WPSClientSession.java:354)
	at org.n52.geoprocessing.wps.client.WPSClientSession.execute(WPSClientSession.java:347)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess$runProcess$processOutput$2.invoke(WPSProcess.kt:104)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess$runProcess$processOutput$2.invoke(WPSProcess.kt:102)
	at org.n.riesgos.asyncwrapper.utils.RetryUtilsKt.retry(RetryUtils.kt:22)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess.runProcess(WPSProcess.kt:102)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:286)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:203)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:66)
	at org.n.riesgos.asyncwrapper.events.OrderMessageHandler.handleMessage(OrderMessageHandler.kt:23)
	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[11,34]
Message: unexpected tag: {http://www.opengis.net/wps/1.0.0}ExceptionReport
	at org.n52.iceland.util.XmlFactories.unexpectedTag(XmlFactories.java:142)
	at org.n52.geoprocessing.wps.client.decoder.stream.GetStatusResponse100Decoder.readExecuteResponse(GetStatusResponse100Decoder.java:101)
	at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readExecuteResponse(WPSResponseReader.java:75)
	at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readElement(WPSResponseReader.java:64)
	at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:618)
	... 16 common frames omitted
2023-05-15 09:11:10,767 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 1)
2023-05-15 09:11:10,880 [tsunami-asyncwrapper_new-order_subscription] WARN  WPSProcess: wps process returned an exception, retryable: true
org.n52.geoprocessing.wps.client.WPSClientException: Could not decode Inputstream.
	at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:620)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveResponseOrExceptionReportInpustream(WPSClientSession.java:588)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveDataViaPOST(WPSClientSession.java:659)
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveExecuteResponseViaPOST(WPSClientSession.java:690)
	at org.n52.geoprocessing.wps.client.WPSClientSession.execute(WPSClientSession.java:354)
	at org.n52.geoprocessing.wps.client.WPSClientSession.execute(WPSClientSession.java:347)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess$runProcess$processOutput$2.invoke(WPSProcess.kt:104)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess$runProcess$processOutput$2.invoke(WPSProcess.kt:102)
	at org.n.riesgos.asyncwrapper.utils.RetryUtilsKt.retry(RetryUtils.kt:22)
	at org.n.riesgos.asyncwrapper.process.wps.WPSProcess.runProcess(WPSProcess.kt:102)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.runOneJob(AbstractWrapper.kt:286)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.fillConstraintsAndRun(AbstractWrapper.kt:203)
	at org.n.riesgos.asyncwrapper.dummy.AbstractWrapper.run(AbstractWrapper.kt:66)
	at org.n.riesgos.asyncwrapper.events.OrderMessageHandler.handleMessage(OrderMessageHandler.kt:23)
	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.receiveMessages(PulsarConsumer.kt:22)
	at org.n.riesgos.asyncwrapper.pulsar.PulsarConsumer.run(PulsarConsumer.kt:13)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[11,34]
Message: unexpected tag: {http://www.opengis.net/wps/1.0.0}ExceptionReport
	at org.n52.iceland.util.XmlFactories.unexpectedTag(XmlFactories.java:142)
	at org.n52.geoprocessing.wps.client.decoder.stream.GetStatusResponse100Decoder.readExecuteResponse(GetStatusResponse100Decoder.java:101)
	at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readExecuteResponse(WPSResponseReader.java:75)
	at org.n52.geoprocessing.wps.client.xml.WPSResponseReader.readElement(WPSResponseReader.java:64)
	at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:618)
	... 16 common frames omitted
2023-05-15 09:11:11,881 [tsunami-asyncwrapper_new-order_subscription] INFO  WPSProcess: execute WPS process get_tsunamap (retries: 2)
2023-05-15 09:11:26,380 [pulsar-timer-5-1] INFO  org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: [new-order] [tsunami-asyncwrapper_new-order_subscription] [c7ee3] Prefetched messages: 0 --- Consume throughput received: 0.02 msgs/s --- 0.00 Mbit/s --- Ack sent rate: 0.00 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0
```

**Comment by arnevogt** [comment]
@MichaelLangbein 
#100 only changed the logging - unless the WPS client has really weird behavior. I will look into the clients code.

Confirm that the wrapper is still stuck if the input values don't match a pre-calculated simulation. The issue itself is related to the PyWPS/get_tsunamap process. From the log you can see that WPS (not the wrapper) is stuck during the third retry. I don't know why the WPS behaves like this, but this is repeatable also with the GIST I wrote. 
I think the only way to prevent this state in the wrapper (besides using correct input values) is to implement a timeout. 
Maybe it makes sense to create a new, separate issue for that(?)

**Comment by MichaelLangbein** [comment]
> Maybe it makes sense to create a new, separate issue for that(?)

I've created an issue at https://gitlab.awi.de/tsunawi/tsunawi/-/issues/2 , but since this is a private repo, I'm keeping this one open.
@bpross-52n : I believe you have write-access to that repo, right?

**Comment by arnevogt** [comment]
I also created a new issue regarding the timeout for the wrapper because the case that a WPS process is stuck can (in theory) happen with all processes.

#101

**Comment by MichaelLangbein** [comment]
> Confirm that the wrapper is still stuck if the input values don't match a pre-calculated simulation. The issue itself is related to the PyWPS/get_tsunamap process. From the log you can see that WPS (not the wrapper) is stuck during the third retry. I don't know why the WPS behaves like this, but this is repeatable also with the GIST I wrote.

Alright, I can confirm that the wrapper is still stuck if the input values don't match a pre-calculated simulation.

I am, however, not certain that the issue is with PyWPS/get_tsunamap. Simply sending an execute-request with postman several times does not cause py-wps to stop responding. I can reproduce the error only with the production-environment and with your GIST.

**Comment by arnevogt** [comment]
@MichaelLangbein 
I debugged a little bit into the WPS Client's code. 
The client does not expect the nested _wps:ExceptionReport_  tag. Tomorrow I will check if this another issue with the client or the response document is invalid. 
Unfortunately that parsing error hides the exception that caused the failure of the WPS process.
